ZoneOut/ZoneOut/Models/Councellor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Councellor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
    }
}

ZoneOut/ZoneOut/Controllers/CouncellorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZoneOut.Models;

namespace ZoneOut.Controllers
{
    public class CouncellorsController : Controller
    {
        private ZoneOutDatabaseEntities db = new ZoneOutDatabaseEntities();

        // GET: Councellors
        public async Task<ActionResult> Index()
        {
            return View(await db.Councellors.ToListAsync());
        }

        // GET: Councellors/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Councellor councellor = await db.Councellors.FindAsync(id);
            if (councellor == null)
            {
                return HttpNotFound();
            }
            return View(councellor);
        }
        /*
        // GET: Councellors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Councellors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Address,Suburb,State,Postcode,Phone,Details,Latitude,Longitude")] Councellor councellor)
        {
            if (ModelState.IsValid)
            {
                db.Councellors.Add(councellor);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(councellor);
        }

        // GET: Councellors/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Councellor councellor = await db.Councellors.FindAsync(id);
            if (councellor == null)
            {
                return HttpNotFound();
            }
            return View(councellor);
        }

        // POST: Councellors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Address,Suburb,State,Postcode,Phone,Details,Latitude,Longitude")] Councellor councellor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(councellor).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(councellor);
        }

        // GET: Councellors/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Councellor councellor = await db.Councellors.FindAsync(id);
            if (councellor == null)
            {
                return HttpNotFound();
            }
            return View(councellor);
        }

        // POST: Councellors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Councellor councellor = await db.Councellors.FindAsync(id);
            db.Councellors.Remove(councellor);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZoneOut/ZoneOut/Views/Councellors/Details.cshtml
@model ZoneOut.Models.Councellor

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.ActionLink("ZONE OUT POINT", "Index", "Home") >
    SUGGESTIONS >
    @Html.ActionLink("COUNCELLORS","Index","Councellors") >
    @Model.Name
</div>
<div style="margin-left:3%;margin-right:3%">
    <div class="row">
        <div class="col l4 m12 card blue lighten-5">
            <div id="map-block"></div>
        </div>
        <div class="col l3 offset-l1 m12 card blue lighten-5">
            <h4>@Html.DisplayFor(model => model.Name)</h4>
            <hr />
            <div>
                <span style="font-weight:bold">Address: </span>
                @Html.DisplayFor(model => model.Address),
            </div>
            <div>
                <span style="font-weight:bold">Type: </span>
                @Html.DisplayFor(model => model.Type)
            </div>
        </div>
        <div class="col l3 offset-l1 m12 card blue lighten-5">
            <div class="col m3 s6"></div>
            <select id="mode">
                <option value="DRIVING">Driving</option>
                <option value="TRANSIT">Transit</option>
                <option value="WALKING">Walking</option>
                <option value="BICYCLING">Bicycling</option>
            </select>
            <div id="right-panel" style="font-size:small"></div>
        </div>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>
@section Scripts{
    <script>
        var map, infoWindow;
        var destlat = @Model.Latitude;
        var destlng= @Model.Longitude;
        var lat = parseFloat(localStorage.getItem('lat'));
        var lng = parseFloat(localStorage.getItem('lng'));
        function initMap() {
            map = new google.maps.Map(document.getElementById('map-block'), {
                zoom: 12,
                center: { lat: lat, lng: lng },
                mapTypeControl: true,
                mapTypeControlOptions: {
                    style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
                    position: google.maps.ControlPosition.TOP_CENTER
                },
                zoomControl: true,
                zoomControlOptions: {
                    position: google.maps.ControlPosition.LEFT_CENTER
                },
                scaleControl: true,
                streetViewControl: true,
                streetViewControlOptions: {
                    position: google.maps.ControlPosition.LEFT_TOP
                },
                fullscreenControl: true
            });

            infoWindow = new google.maps.InfoWindow;
            map.setCenter({'lat':lat,'lng':lng});
            var centermarker = new google.maps.Marker({
                position: { 'lat': lat, 'lng': lng },
                map: map,
                title: 'You are here!'
            });
            var marker = new google.maps.Marker({
                position: { 'lat': destlat, 'lng': destlng },
                map: map,
                title: '@Model.Name'
            });
            var directionsDisplay = new google.maps.DirectionsRenderer;
            var directionsService = new google.maps.DirectionsService;
            directionsDisplay.setMap(map);
            directionsDisplay.setPanel(document.getElementById('right-panel'));
            calculateAndDisplayRoute(directionsService, directionsDisplay);
            document.getElementById('mode').addEventListener('change', function () {
                calculateAndDisplayRoute(directionsService, directionsDisplay);
            });
        }

        function calculateAndDisplayRoute(directionsService, directionsDisplay) {
            var selectedMode = document.getElementById('mode').value;
            directionsService.route({
                origin: { lat: lat, lng: lng },  // Haight.
                destination: { lat: destlat, lng: destlng },  // Ocean Beach.
                travelMode: google.maps.TravelMode[selectedMode]
            }, function (response, status) {
                if (status == 'OK') {
                    directionsDisplay.setDirections(response);
                    $('footer').css({ 'position': 'relative' });
                } else {
                    window.alert('Directions request failed due to ' + status);
                }
            });
        }
        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                'Error: The Geolocation service failed.' :
                'Error: Your browser doesn\'t support geolocation.');
            infoWindow.open(map);
        }

    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCINgZahvqcpiICfKm4sNe_yWWMq128EpI&callback=initMap">
    </script>
    <script>
        $(function () {
            if (window.screen.availWidth > 800) {
                $('#map-block').css({
                    'left': 0,
                    'height': window.screen.availHeight * 0.6,
                    'width': $('.row').width() * 0.35
                });
            } else {
                $('#map-block').css({
                    'left': 0,
                    'height': window.screen.availHeight * 0.6,
                    'width': window.screen.availWidth * 0.9
                });
            }
            $('#nav-item-suggest').addClass('active');
            $('select').formSelect();
        });
    </script>
}

ZoneOut/ZoneOut/Views/Councellors/Index.cshtml
@model IEnumerable<ZoneOut.Models.Councellor>
@{
    ViewBag.Title = "Councellors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles{
    <link rel="stylesheet" href="~/Content/DataTables/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/Content/DataTables/css/select.bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/map-icons.css" />
    <link rel="stylesheet" href="~/Content/maps-index.css" />
}
<div>
    @Html.ActionLink("ZONE OUT POINT", "Index", "Home") >
    SUGGESTIONS >
    COUNCELLORS
</div>
<div style="margin-left:3%;margin-right:3%">
    <h4 style="font-weight:bold">Councellors Near You</h4>
    <h6>Tips: Counselling service can help people improve their mental health. </h6>
    <div class="row">

        <div class="col l5 m12 card blue lighten-5">

            <div class="pac-card" id="pac-card" style="width:inherit">
                <h6 style="font-weight:bold">
                    search another location
                    <input id="pac-input" type="text" placeholder="Enter a location" style="width:inherit">
                </h6>
            </div>
            <div id="map-block"></div>
        </div>
        <div class="col l6 offset-l1 m12 card blue lighten-5" style="font-size:smaller">
            <table class="table cards" id="data">
                <thead hidden="hidden">
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            Category
                        </th>
                        <th>Distance</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="table-body"></tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript" src="~/Scripts/maps-coun-generate-data-tables.js"></script>
    <script type="text/javascript" src="~/Scripts/maps-coun-get-data.js"></script>
    <script type="text/javascript" src="~/Scripts/maps-init-map.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCINgZahvqcpiICfKm4sNe_yWWMq128EpI&libraries=places&callback=initMap"></script>
    <script type="text/javascript" src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Scripts/DataTables/dataTables.material.min.js"></script>
    <!--script type="text/javascript" src="~/Scripts/DataTables/dataTables.bootstrap4.min.js"></script>-->
    <script type="text/javascript" src="~/Scripts/DataTables/dataTables.select.min.js"></script>
    <script type="text/javascript" src="~/Scripts/map-icons.js"></script>
    <script>
        $('#nav-item-suggest').addClass('active');
    </script>
}