ZoneOut/ZoneOut/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ZoneOut.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        public string UserName  { get { return "zoneout"; } }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember?")]
        public bool RememberMe { get; set; }
    }
}

ZoneOut/ZoneOut/Controllers/ColoringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZoneOut.Models;

namespace ZoneOut.Controllers
{
    public class ColoringController : Controller
    {
        private readonly int NumberOfPictures = 24;
        // GET: Coloring
        public ActionResult Index()
        {
            List<Coloring> Colorings = new List<Coloring>();
            for(int i=0; i < NumberOfPictures; i++)
            {
                Colorings.Add(new Coloring { Id = i ,Url="/Canvas/image"+i+".jpg"});
            }
            return View(Colorings);
        }
        
        public ActionResult ColoringGameInternalRandom()
        {
            ViewBag.Message = "Coloring Game";
            var imgId = new Random().Next(NumberOfPictures);
            var Picture = new Coloring { Id = imgId, Url = "/Canvas/image" + imgId + ".jpg" };
            return View(Picture);
        }
        public ActionResult ColoringGameInternalSelected(int picId)
        {
            var Picture = new Coloring { Id = picId,Url="/Canvas/image"+picId+".jpg" };
            return View(Picture);
        }
        public ActionResult ColoringGameExternal()
        {
            return View();
        }
    }
}

ZoneOut/ZoneOut/Controllers/HobbyClassController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZoneOut.Models;

namespace ZoneOut.Controllers
{
    public class HobbyClassController : Controller
    {
        private ZoneOutDatabaseEntities db = new ZoneOutDatabaseEntities();

        // GET: HobbyClass
        public async Task<ActionResult> Index()
        {
            return View(await db.Hobby_Class.ToListAsync());
        }

        // GET: HobbyClass/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hobby_Class hobby_Class = await db.Hobby_Class.FindAsync(id);
            if (hobby_Class == null)
            {
                return HttpNotFound();
            }
            return View(hobby_Class);
        }
        /*
        // GET: HobbyClass/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HobbyClass/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Address,Suburb,Postcode,State,Category,LGA,Region")] Hobby_Class hobby_Class)
        {
            if (ModelState.IsValid)
            {
                db.Hobby_Class.Add(hobby_Class);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(hobby_Class);
        }

        // GET: HobbyClass/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hobby_Class hobby_Class = await db.Hobby_Class.FindAsync(id);
            if (hobby_Class == null)
            {
                return HttpNotFound();
            }
            return View(hobby_Class);
        }

        // POST: HobbyClass/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Address,Suburb,Postcode,State,Category,LGA,Region")] Hobby_Class hobby_Class)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hobby_Class).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(hobby_Class);
        }

        // GET: HobbyClass/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hobby_Class hobby_Class = await db.Hobby_Class.FindAsync(id);
            if (hobby_Class == null)
            {
                return HttpNotFound();
            }
            return View(hobby_Class);
        }

        // POST: HobbyClass/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Hobby_Class hobby_Class = await db.Hobby_Class.FindAsync(id);
            db.Hobby_Class.Remove(hobby_Class);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZoneOut/ZoneOut/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using ZoneOut.Models;

namespace ZoneOut.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly double COOKIE_EXPIRES = 30;

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Infinite Loops";
            return View();
        }
        public ActionResult Statistics()
        {
            ViewBag.Message = "How can art (and other activities) help me?";
            return View();
        }
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.UserName.Equals("zoneout") && model.Password.Equals("infinite081Loop"))
            {
                string userData = new JavaScriptSerializer().Serialize(model);
                var ticket = new FormsAuthenticationTicket(1, model.UserName, DateTime.Now, DateTime.Now.AddDays(COOKIE_EXPIRES), false, userData, FormsAuthentication.FormsCookiePath);
                string encrypt = FormsAuthentication.Encrypt(ticket);
                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypt);
                if (model.RememberMe)
                {
                    cookie.Expires = DateTime.Now.AddDays(COOKIE_EXPIRES);
                }
                Response.Cookies.Remove(cookie.Name);
                Response.Cookies.Add(cookie);

                if (string.IsNullOrEmpty(returnUrl))
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                    return Redirect(returnUrl);
            }
            else
            {
                ModelState.AddModelError("", "Invalid Login");
                return View(model);
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Redirect(FormsAuthentication.LoginUrl);
        }
        public ActionResult Quiz()
        {
            return View();
        }
        public ActionResult Error(String aspxerrorpath)
        {
            return View();
        }
    }
}

ZoneOut/ZoneOut/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZoneOut.Models;

namespace ZoneOut.Controllers
{
    public class PlacesController : Controller
    {
        private ZoneOutDatabaseEntities db = new ZoneOutDatabaseEntities();

        // GET: Places
        public async Task<ActionResult> Index()
        {
            return View(await db.Places.ToListAsync());
        }

        // GET: Places/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = await db.Places.FindAsync(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }
        /*
        // GET: Places/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Location,Description,Address,Suburb,State,Postcode,Latitude,Longitude")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Places.Add(place);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(place);
        }

        // GET: Places/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = await db.Places.FindAsync(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Location,Description,Address,Suburb,State,Postcode,Latitude,Longitude")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Entry(place).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(place);
        }

        // GET: Places/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = await db.Places.FindAsync(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Place place = await db.Places.FindAsync(id);
            db.Places.Remove(place);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZoneOut/ZoneOut/Controllers/QuizzesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZoneOut.Models;

namespace ZoneOut.Controllers
{
    public class QuizzesController : Controller
    {
        private ZoneOutDatabaseEntities db = new ZoneOutDatabaseEntities();

        // GET: Quizzes
        public ActionResult Index()
        {
            return View();
        }

        // GET: Quizzes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quiz quiz = await db.Quizs.FindAsync(id);
            if (quiz == null)
            {
                return HttpNotFound();
            }
            return View(quiz);
        }
        public async Task<ActionResult> PlanQuiz()
        {
            return View(await db.Quizs.Where(m => m.Mark==5).ToListAsync());
        }
        public ActionResult Calculator()
        {
            CalculatorViewModel model = new CalculatorViewModel();
            model.Result = 168;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Calculator([Bind] CalculatorViewModel model)
        {
            double res = 168 - model.Sleep * 7 - model.Grooming * 7 - model.Meals * 7 -
                model.Travel * 7 - model.Activities - model.Errands * 7 - model.Work -
                model.Class - model.Friends - model.Computer * 7;
            if (res <= 0.01) res = 0.01;
            model.Result = res;
            return View(model);
        }
        public ActionResult Strategies() => View();
        public ActionResult Planning() => View();
        /*
        // GET: Quizzes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quizzes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Question,Mark")] Quiz quiz)
        {
            if (ModelState.IsValid)
            {
                db.Quizs.Add(quiz);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(quiz);
        }

        // GET: Quizzes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quiz quiz = await db.Quizs.FindAsync(id);
            if (quiz == null)
            {
                return HttpNotFound();
            }
            return View(quiz);
        }

        // POST: Quizzes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Question,Mark")] Quiz quiz)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quiz).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(quiz);
        }

        // GET: Quizzes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quiz quiz = await db.Quizs.FindAsync(id);
            if (quiz == null)
            {
                return HttpNotFound();
            }
            return View(quiz);
        }

        // POST: Quizzes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Quiz quiz = await db.Quizs.FindAsync(id);
            db.Quizs.Remove(quiz);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        */
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZoneOut/ZoneOut/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    Here at Zone Out, we are driven by a single goal;
    to do our part in making the world a better place for all.
    Our decision making process is informed by comprehensive
    empirical studies and high quality data evaluation.
    We strive to build productive relationships and make
    a positive impact with all of our pursuits.
</p>
@section Scripts
{
    <script>
        $(function () {
            $('#nav-item-about').addClass('active');
        });
    </script>
}

ZoneOut/ZoneOut/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section Styles{
    <style>
        body {
            background: url('/Images/bg.jpg') no-repeat right top fixed;
        }

        .carousel {
            margin-bottom: 4rem;
        }
        /* Since positioning the image, we need to help out the caption */
        .carousel-caption {
            bottom: 3rem;
            z-index: 15;
        }

        /* Declare heights because of positioning of img element */
        .carousel-item {
            width: 100%;
            height:auto;
        }

        .carousel.carousel-item > img {
            position: relative;
            top: 0;
            left: 0;
        }

        .material-icons {
            font-family: 'Material Icons';
            font-weight: normal;
            font-style: normal;
            font-size: 24px;
            line-height: 1;
            letter-spacing: normal;
            text-transform: none;
            display: inline-block;
            white-space: nowrap;
            word-wrap: normal;
            direction: ltr;
            -moz-font-feature-settings: 'liga';
            -moz-osx-font-smoothing: grayscale;
        }

        .middle-indicator {
            position: absolute;
            top: 50%;
        }

        .middle-indicator-text {
            font-size: 4.2rem;
        }

        a.middle-indicator-text {
            color: white !important;
        }

        .content-indicator {
            width: 64px;
            height: 64px;
            background: none;
            -moz-border-radius: 50px;
            -webkit-border-radius: 50px;
            border-radius: 50px;
        }

        .overlay {
            position: absolute;
            top: 30%;
            bottom: 0;
            left: 0;
            right: 0;
            height: 50%;
            width: 100%;
            opacity: 0;
            transition: .5s ease;
            background-color: #c51162;
        }

        .card:hover .overlay {
            opacity: 1;
        }
    </style>
}

<div style="margin-top:1%">
    <div class="row">
        <div class="col s12 m12 offset-l3 l8 no-padding" id="carousel">
            <div class="carousel carousel-slider center z-depth-5" data-indicators="true">
                <div class="carousel-fixed-item center middle-indicator">
                    <div class="left">
                        <a href="Previo" class="movePrevCarousel middle-indicator-text waves-effect waves-light content-indicator"><i class="material-icons left  middle-indicator-text">chevron_left</i></a>
                    </div>
                    <div class="right">
                        <a href="Siguiente" class=" moveNextCarousel middle-indicator-text waves-effect waves-light content-indicator"><i class="material-icons right middle-indicator-text">chevron_right</i></a>
                    </div>
                </div>
                <a class="carousel-item" href="#">
                    <img class="carousel-image" src="/Images/background-1.jpg" alt="First slide">
                </a>
                <a class="carousel-item" href="#">
                    <img class="carousel-image" src="/Images/background-2.jpg" alt="Second slide">
                </a>
                <a class="carousel-item" href="#">
                    <img class="carousel-image" src="/Images/background-3.jpg" alt="Third slide">
                </a>
            </div>
        </div>
    </div>
</div>
<div class="card-panel col l4 m12 s12" id="block-besides-carousel" style="
            background-color:rgba(255,64,129,0.7);
            position:absolute;padding:2%">
    <div id="text-besides-carousel" class="flow-text white-text">Are you an international university student?</div>
    <div class="center-align">
        @Html.ActionLink("Learn More", "Statistics","Home",new { },
       new { @id="btn-main-learn-more", @class= "waves-effect waves-light btn-large pulse flow-text white-text" })
    </div>
</div>



<div id="before-cards" class="pink darken-1">
    <div style="height:10%"></div>
    <h4 class="center-align" style="color:white;font-weight:bold">OUR SERVICES</h4>
</div>
<div style="margin-top:15px;margin-bottom:15px">
    <div class="row">
        <div class="col s12 m6 l4">
            <div class="card z-depth-5 pink accent-4" style="padding:5px">
                <img class="card-img-top" src="~/Images/coloring-book-1.jpg" style="width:100%;height:100%" />
                <div class="overlay" style="padding:2pt">
                    <p id="card-text-game" class="flow-text white-text" style="font-size: medium">
                        Art therapy is a therapy which helps people improve their mental health through creativity.
                        People can express their feelings and expression through art can be healing. It also
                        helps people to release their stress. 
                    </p>
                    <br />
                    <div class="center-align">
                        @Html.ActionLink("Learn More", "Index", "Coloring", new { },
                       new {@class= "waves-effect waves-light btn-small pulse" })
                    </div>
                </div>
                <div>
                    <h3 class="card-title white-text" style="font-weight:bold">Art Games</h3>
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card z-depth-5 pink accent-4" style="padding:5px">
                <img class="card-img-top" src="~/Images/stat.png" style="width:100%;height:100%" />
                <div class="overlay" style="padding:2pt">
                    <p id="card-text-stat" class="flow-text white-text" style="font-size: medium">
                        Other than making random doodles on margin of pages to kill time, 
                        you do not express yourself with art as you used to as a kid.
                        looking at it or even making it to our brain and overall mental health.
                    </p>
                    <br />
                    <div class="center-align">
                        @Html.ActionLink("Learn More", "Statistics", "Home", new { },
                       new {@class= "waves-effect waves-light btn-small pulse" })
                    </div>
                </div>
                <div>
                    <h3 class="card-title white-text" style="font-weight:bold">Statistics</h3>
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card z-depth-5 pink accent-4" style="padding:5px">
                <img class="card-img-top" src="~/Images/time.jpg" style="width:100%;height:100%" />
                <div class="overlay" style="padding:2pt">
                    <p id="card-text-stat" class="flow-text white-text" style="font-size: medium">
                        Time management is the process of planning and exercising conscious 
                        control of time spent on specific activities, especially to increase 
                        effectiveness, efficiency or productivity. 
                    </p>
                    <br />
                    <div class="center-align">
                        @Html.ActionLink("Learn More", "Index", "Quizzes", new { },
                       new {@class= "waves-effect waves-light btn-small pulse" })
                    </div>
                </div>
                <div>
                    <h3 class="card-title white-text" style="font-weight:bold">Time Management</h3>
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card z-depth-5 pink accent-4" style="padding:5px">
                <img class="card-img-top" src="~/Images/hobby-bg.jpg" style="width:100%;height:100%" />
                <div class="overlay" style="padding:2pt">
                    <p id="card-text-stat" class="flow-text white-text" style="font-size: medium">
                        Join some hobby classes, you can make friends,
                        reduce academic stress and improve mental health.
                    </p>
                    <br />
                    <div class="center-align">
                        @Html.ActionLink("Learn More", "Index", "HobbyClass", new { },
                       new {@class= "waves-effect waves-light btn-small pulse" })
                    </div>
                </div>
                <div>
                    <h3 class="card-title white-text" style="font-weight:bold">Hobby Classes</h3>
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card z-depth-5 pink accent-4" style="padding:5px">
                <img class="card-img-top" src="~/Images/place.jpg" style="width:100%;height:100%" />
                <div class="overlay" style="padding:2pt">
                    <p id="card-text-stat" class="flow-text white-text" style="font-size: medium">
                        Beautiful attractions can make people feel relaxed and improve their mental health.
                    </p>
                    <br />
                    <div class="center-align">
                        @Html.ActionLink("Learn More", "Index", "Places", new { },
                       new {@class= "waves-effect waves-light btn-small pulse" })
                    </div>
                </div>
                <div>
                    <h3 class="card-title white-text" style="font-weight:bold">Interesting Places</h3>
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card z-depth-5 pink accent-4" style="padding:5px">
                <img class="card-img-top" src="~/Images/quiz.jpg" style="width:100%;height:100%" />
                <div class="overlay" style="padding:2pt">
                    <p id="card-text-stat" class="flow-text white-text" style="font-size:medium">
                        Counselling service can help people improve their mental health.
                    </p>
                    <br />
                    <div class="center-align">
                        @Html.ActionLink("Learn More", "Index", "Councellors", new { },
                       new {@class= "waves-effect waves-light btn-small pulse" })
                    </div>
                </div>
                <div>
                    <h3 class="card-title white-text" style="font-weight:bold">Councellors</h3>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(function () {
            var i = 0;
            const carouselText = ['Are you an international university student?',
                'Are you facing any problems regarding mental health?',
                'ZONE OUT POINT will help you cope with stress.'];
            $('#nav-item-home').addClass('active');
            $('.carousel.carousel-slider').carousel({
                fullWidth: true,
                duration: 200
            });
            setTimeout(autoplay, 3500);
            function autoplay() {
                $('.carousel').carousel('next');
                i += 1;
                if (i > 2) i = 0;
                if (i === 2) $('#btn-main-learn-more').show(); else $('#btn-main-learn-more').hide();
                $('#text-besides-carousel').text(carouselText[i]);
                setTimeout(autoplay, 3500);
            }
            $('.moveNextCarousel').click(function (e) {
                e.preventDefault();
                e.stopPropagation();
                i += 1;
                if (i > 2) i = 0;
                if (i === 2) $('#btn-main-learn-more').show(); else $('#btn-main-learn-more').hide();
                $('#text-besides-carousel').text(carouselText[i]);
                $('.carousel').carousel('next');
            });

            // move prev carousel
            $('.movePrevCarousel').click(function (e) {
                e.preventDefault();
                e.stopPropagation();
                i -= 1;
                if (i < 0) i = 2;
                if (i === 2) $('#btn-main-learn-more').show(); else $('#btn-main-learn-more').hide();
                $('#text-besides-carousel').text(carouselText[i]);
                $('.carousel').carousel('prev');
            });
            $('#before-cards').css({ 'height': $('#carousel').height() / 4 });
            $('#btn-main-learn-more').hide();
            $('#block-besides-carousel').css({
                'color': 'white',
                'top': $('#carousel').height() * .4,
                'left': $('#carousel').width() / 12,
                'height': $('#carousel').height() * .4,
                'font-size': $('#carousel').height() / 10
            });
            if ($(document).width() > 800) {

                $('#block-besides-carousel').css({
                    'width': $(document).width() / 3
                });
            } else {
                $('#carousel').css({ 'height': window.screen.availHeight * 0.85 });
                $('.carousel').css({ 'height': window.screen.availHeight * 0.85 });
                $('.carousel-item').css({ 'height': window.screen.availHeight * 0.85 });
                $('.carousel-image').css({
                    'height': window.screen.availHeight * 0.85,
                    'width': 'auto',
                    'margin-left': '-60%'
                });
                $('#block-besides-carousel').css({
                    'width': $(document).width() * .8,
                    'top': $('#carousel').height() * .5
                });
                $('#btn-main-learn-more').addClass('btn-small');
            }
        });
    </script>
}